FROM nikolaik/python-nodejs:python3.12-nodejs18
WORKDIR /Node-Audio-getter
COPY . .
RUN npm i --save-dev nodemon
RUN pip install transformers torch
RUN pip install click 
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
RUN apt-get update && apt-get install -y ffmpeg

EXPOSE 3000

CMD [ "npm" ,"start"]
