FROM nikolaik/python-nodejs:python3.12-nodejs18
WORKDIR /Node-Audio-getter
COPY . .
RUN npm i --save-dev nodemon
RUN pip install transformers torch
RUN pip install click 

EXPOSE 3000

CMD [ "npm" ,"start"]
